import React from 'react'
import './globals.css'
import { Capriola } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
const capriola = Capriola({
  subsets: ['latin'],
  weight: '400',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={capriola.className}>{children}</body>
    </html>
  )
}
